import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/_global/Header";
import Footer from "@/components/_global/Footer";

export const metadata: Metadata = {
  title: "Brainwave.io",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
			<body>
				<div className="container mx-auto justify-center">
					<Header />
					{children}
				</div>
				
				<Footer />
			</body>
		</html>
  );
}
